### ISSUE TITLE
Add @NYU to the google list of domains

### ISSUE THREAD

**Issue by MadMattAu** [thunderbird/autoconfig#111]
I was looking at https://support.mozilla.org/en-US/questions/1444845 where it became apparent that standard gmail settings should be what is required, instead of nothing from the auto config.  Nothing is what you get when the autoconfiguration runs because there is no response from any server to any of the attempts to detect settings.So even if ALL @NYU email account are not gmail.  We will still be improving the odds of a satisfied customer because the current situation is a full manual configuration in all cases.

mail.setup: imap.nyu.edu:993 socketType=3 imap: timeout GuessConfig.sys.mjs:558:21
mail.setup: smtp.nyu.edu:465 socketType=3 smtp: timeout GuessConfig.sys.mjs:558:21
mail.setup: mail.nyu.edu:993 socketType=3 imap: timeout GuessConfig.sys.mjs:558:21
mail.setup: mail.nyu.edu:465 socketType=3 smtp: timeout GuessConfig.sys.mjs:558:21
mail.setup: nyu.edu:993 socketType=3 imap: timeout GuessConfig.sys.mjs:558:21
mail.setup: nyu.edu:465 socketType=3 smtp: timeout GuessConfig.sys.mjs:558:21
mail.setup: imap.nyu.edu:143 socketType=2 imap: timeout GuessConfig.sys.mjs:558:21
mail.setup: smtp.nyu.edu:587 socketType=2 smtp: timeout GuessConfig.sys.mjs:558:21
mail.setup: mail.nyu.edu:143 socketType=2 imap: timeout GuessConfig.sys.mjs:558:21
mail.setup: smtp.nyu.edu:25 socketType=2 smtp: timeout GuessConfig.sys.mjs:558:21
mail.setup: nyu.edu:143 socketType=2 imap: timeout GuessConfig.sys.mjs:558:21
mail.setup: mail.nyu.edu:587 socketType=2 smtp: timeout GuessConfig.sys.mjs:558:21
mail.setup: mail.nyu.edu:25 socketType=2 smtp: timeout GuessConfig.sys.mjs:558:21
mail.setup: pop.nyu.edu:995 socketType=3 pop3: timeout GuessConfig.sys.mjs:558:21
mail.setup: nyu.edu:587 socketType=2 smtp: timeout GuessConfig.sys.mjs:558:21
mail.setup: mail.nyu.edu:995 socketType=3 pop3: timeout GuessConfig.sys.mjs:558:21
mail.setup: nyu.edu:25 socketType=2 smtp: timeout GuessConfig.sys.mjs:558:21
mail.setup: nyu.edu:995 socketType=3 pop3: timeout GuessConfig.sys.mjs:558:21
mail.setup: smtp.nyu.edu:587 socketType=0 smtp: timeout GuessConfig.sys.mjs:558:21
mail.setup: smtp.nyu.edu:25 socketType=0 smtp: timeout GuessConfig.sys.mjs:558:21
mail.setup: pop.nyu.edu:110 socketType=2 pop3: timeout GuessConfig.sys.mjs:558:21
mail.setup: mail.nyu.edu:587 socketType=0 smtp: timeout GuessConfig.sys.mjs:558:21
mail.setup: mail.nyu.edu:110 socketType=2 pop3: timeout GuessConfig.sys.mjs:558:21
mail.setup: mail.nyu.edu:25 socketType=0 smtp: timeout GuessConfig.sys.mjs:558:21
mail.setup: nyu.edu:110 socketType=2 pop3: timeout GuessConfig.sys.mjs:558:21
mail.setup: nyu.edu:587 socketType=0 smtp: timeout GuessConfig.sys.mjs:558:21
mail.setup: imap.nyu.edu:143 socketType=0 imap: timeout GuessConfig.sys.mjs:558:21
mail.setup: nyu.edu:25 socketType=0 smtp: timeout GuessConfig.sys.mjs:558:21
mail.setup: guessConfig failed: Can't find a server accountSetup.js:877:29
mail.setup: 
Object { _message: "Hostname is empty or contains forbidden characters. Only letters, numbers, - and . are allowed.", stack: "Exception@resource:///modules/accountcreation/AccountCreationUtils.sys.mjs:114:3\nMalformedException@resource:///modules/accountcreation/Sanitizer.sys.mjs:241:34\nhostname@resource:///modules/accountcreation/Sanitizer.sys.mjs:115:13\ngetUserConfig@chrome://messenger/content/accountcreation/accountSetup.js:1618:44\nvalidateManualEditComplete@chrome://messenger/content/accountcreation/accountSetup.js:2086:31\neditConfigDetails@chrome://messenger/content/accountcreation/accountSetup.js:1731:10\n_guessConfig/self._abortable<@chrome://messenger/content/accountcreation/accountSetup.js:879:14\ncheckDone@resource:///modules/accountcreation/GuessConfig.sys.mjs:157:22\noutgoingError@resource:///modules/accountcreation/GuessConfig.sys.mjs:272:5\n_checkFinished@resource:///modules/accountcreation/GuessConfig.sys.mjs:674:12\n_tryAll/</thisTry.abortable<@resource:///modules/accountcreation/GuessConfig.sys.mjs:560:16\n_error@resource:///modules/accountcreation/GuessConfig.sys.mjs:1133:18\ntimeoutFunc@resource:///modules/accountcreation/GuessConfig.sys.mjs:1138:13\nnotify@resource://gre/modules/Timer.sys.mjs:49:17\nnsIPrompt_promptPassword@resource:///modules/MsgAsyncPrompter.sys.mjs:593:15\npromptPassword@resource:///modules/MsgAsyncPrompter.sys.mjs:377:40\n_promiseAuthPrompt/<@resource:///modules/MsgAsyncPrompter.sys.mjs:42:18\n_promiseAuthPrompt@resource:///modules/MsgAsyncPrompter.sys.mjs:40:12\nrun@resource:///modules/MsgAsyncPrompter.sys.mjs:65:23\n" }
accountSetup.js:1621:27
mail.setup: 
Object { _message: "Hostname is empty or contains forbidden characters. Only letters, numbers, - and . are allowed.", stack: "Exception@resource:///modules/accountcreation/AccountCreationUtils.sys.mjs:114:3\nMalformedException@resource:///modules/accountcreation/Sanitizer.sys.mjs:241:34\nhostname@resource:///modules/accountcreation/Sanitizer.sys.mjs:115:13\ngetUserConfig@chrome://messenger/content/accountcreation/accountSetup.js:1665:44\nvalidateManualEditComplete@chrome://messenger/content/accountcreation/accountSetup.js:2086:31\neditConfigDetails@chrome://messenger/content/accountcreation/accountSetup.js:1731:10\n_guessConfig/self._abortable<@chrome://messenger/content/accountcreation/accountSetup.js:879:14\ncheckDone@resource:///modules/accountcreation/GuessConfig.sys.mjs:157:22\noutgoingError@resource:///modules/accountcreation/GuessConfig.sys.mjs:272:5\n_checkFinished@resource:///modules/accountcreation/GuessConfig.sys.mjs:674:12\n_tryAll/</thisTry.abortable<@resource:///modules/accountcreation/GuessConfig.sys.mjs:560:16\n_error@resource:///modules/accountcreation/GuessConfig.sys.mjs:1133:18\ntimeoutFunc@resource:///modules/accountcreation/GuessConfig.sys.mjs:1138:13\nnotify@resource://gre/modules/Timer.sys.mjs:49:17\nnsIPrompt_promptPassword@resource:///modules/MsgAsyncPrompter.sys.mjs:593:15\npromptPassword@resource:///modules/MsgAsyncPrompter.sys.mjs:377:40\n_promiseAuthPrompt/<@resource:///modules/MsgAsyncPrompter.sys.mjs:42:18\n_promiseAuthPrompt@resource:///modules/MsgAsyncPrompter.sys.mjs:40:12\nrun@resource:///modules/MsgAsyncPrompter.sys.mjs:65:23\n" }
accountSetup.js:1668:27

**Comment by babolivier** [comment]
Thanks for opening this issue! Ideally, we'd prefer the email service provider to host and maintain an autoconfig file themselves, this way clients such as Thunderbird can detect the most up to date settings, and the provider can provide a more flexible and relevant configuration than we could, since we don't have visibility on their mail infrastructure.

The reference for the autoconfig file format can be found here: https://www.bucksch.org/1/projects/thunderbird/autoconfiguration/config-file-format.html
And one can refer to https://autoconfig.fastmail.com/mail/config-v1.1.xml for a hosted example (or any file in `ispdb/` on this repository).

Have you asked @nyu whether they'd be willing to host such a file themselves? If not and you have a line of contact with their IT team, we'd be happy to assist, feel free to reach out on https://thunderbird.topicbox.com/groups/autoconfig

**Comment by fmartelg** [comment]
I started this thread here https://support.mozilla.org/en-US/questions/1444845 

I reached out to NYU and their response is that they prefer users to access email using a browser for security reasons. 

In short, I don't expect them to help in this case.

**Comment by fmartelg** [comment]
I was finally able to connect. I made two changes at once, so not sure which one did it.

Change 1: I followed the instructions here https://nyu.service-now.com/sp?id=kb_article&sysparm_article=041206915481302&sys_kb_id=5729ffd27449810075e62ca050042e25&spa=1 and enabled access by less secure apps. I suppose they consider TB to be less secure....

Change 2: In TB, when creating the new NYU account, under "User Name" I entered "userName" and not "userName@nyu.edu" even though the instructions provided by NYU say you should enter the full email address...

Hope this helps. 

Thank you for your kind support with this matter.

**Comment by babolivier** [comment]
Sorry both for the time it took me to get back on this. Considering NYU seem hostile towards the idea of hosting their autoconfig file, let's add their domain into ISPDB.

Looking a bit into it, I think I might need more details on what the configuration looks like from a user's point of view. @fmartelg or @MadMattAu, would either of you be happy to send me an email at brendan@thunderbird.net to discuss this?

**Comment by stevenjstromer** [comment]
> Change 2: In TB, when creating the new NYU account, under "User Name" I entered "userName" and not "[userName@nyu.edu](mailto:userName@nyu.edu)" even though the instructions provided by NYU say you should enter the full email address...

Thank you for posting. I attempted your fix 'Change 2' without implementing 'Change 1,' and had instant login success. This is the fix that caused it to work.

Even if NYU is unwilling to host an email client configuration file, they should least update their knowledgebase documentation to reflect this necessary username syntax, to save others hours of frustration.

I will try to get them to do this. Much appreciated!

**Comment by joannakl** [comment]
This issue is closed, but I hope someone is still watching it. 
For years, I used my individual school's email address at NYU (CIMS). Now, we are being forced to switch to the general NYU email, which is a NYU-branded Gmail account. I have no trouble using my personal Gmail account with Thunderbird, but I failed to configure the NYU account. Every time I enter my email address to authenticate, I get 403 Permission Denied error before I even get asked for the password. 
I am curious if NYU email still works for you in Thunderbird @stevenjstromer  and @fmartelg .

**Comment by fmartelg** [comment]
@joannakl my NYU-branded gmail accounts is working on TB.  I think the forbidden error you are getting is related to the user name you are entering.  As noted above: 

> Change 2: In TB, when creating the new NYU account, under "User Name" I entered "userName" and not "[userName@nyu.edu](mailto:userName@nyu.edu)" even though the instructions provided by NYU say you should enter the full email address...

**Comment by woswos** [comment]
@joannakl, you can try this hack: first, register your personal or another working email account with Thunderbird. Next, send yourself an email containing the NYU mail link (https://mail.nyu.edu), and click the link in the email you receive. This will open the link in a new Thunderbird browser window where you can authenticate yourself. After authenticating, try re-registering your NYU email account. You should now be able to register without the 403 Forbidden error since Thunderbird browser has the necessary cookies.

By the way, I took your OSSD S'20 class :) and learned a lot. Thank you again!

<img width="1876" height="984" alt="Image" src="https://github.com/user-attachments/assets/6c437332-e8a6-4faa-8c9e-b00869427d28" />
