### ISSUE TITLE
Outdated config for Provider "mail.telenor.dk"

### ISSUE THREAD

**Issue by Shushangw** [thunderbird/autoconfig#115]
Hi, it appears that the **[mail.telenor.dk](https://autoconfig.thunderbird.net/v1.1/mail.telenor.dk)** provider no longer hosts email service or has migrated to another service. I used the autoconfig URL (e.g., http://autoconfig.email.dk/mail/config-v1.1.xml) to query the autoconfiguration information in real time for a number of domains under this provider, e.g., _email.dk_, _privatmail.dk_, and _info.dk_, whose mail servers in the XML configuration file all point to the "**mail.jubii.dk**" service provider. This may cause service availability problems for client users.

~~In addition, the real-time query result of **[email.it](https://www.email.it/.well-known/autoconfig/mail/config-v1.1.xml)** shows that it only supports SMTPS service, but not STARTTLS listed in [ISPDB](https://autoconfig.thunderbird.net/v1.1/email.it).  However, it should be noted that the configuration file obtained through the autoconfig URL request also has a conflict with the port configuration indicated on its [web page](https://www.email.it/faq).~~

**Comment by cketti** [comment]
Thanks for the report :+1:

But in the future please create one GitHub issue per problem. That makes it easier to work on these issues. I created #116 for the outdated "email.it" config.

**Comment by cketti** [comment]
|Domain|MX record|
|-|-|
|mail.telenor.dk|– (no A record, only CNAME)|
|vip.cybercity.dk|mx01.lytzenitmail.dk|
|post.cybercity.dk|mx01.lytzenitmail.dk|
|email.dk|mx01.lytzenitmail.dk|
|mobil.dk|mx01.dkbal.mailcore.com|
|privatmail.dk|mx01.lytzenitmail.dk|
|info.dk|mx01.lytzenitmail.dk|
|io.dk|mx01.lytzenitmail.dk|
|it.dk|mx01.lytzenitmail.dk|
|film.dk|mx01.dkbal.mailcore.com|
|worldonline.dk|mx01.lytzenitmail.dk|
|wol.dk|– (has A record)|
|1031.inord.dk|– (no A record either)|
|123mail.dk|mx01.lytzenitmail.dk|
|12fuel.dk|mx01.lytzenitmail.dk|
|12mail.dk|mx01.lytzenitmail.dk|
|12move.dk|mx01.lytzenitmail.dk|
|2senior.dk|mx01.lytzenitmail.dk|
|anarki.dk|mx01.lytzenitmail.dk|
|anderledes.dk|mx01.lytzenitmail.dk|
|begavet.dk|mx01.lytzenitmail.dk|
|bitnisse.dk|mx01.lytzenitmail.dk|
|city.dk|mx01.lytzenitmail.dk|
|cool.dk|mx01.lytzenitmail.dk|
|cyberdude.dk|mx01.lytzenitmail.dk|
|cyberjunkie.dk|mx01.lytzenitmail.dk|
|dk2net.dk|mx01.lytzenitmail.dk|
|dk-online.dk|mx01.lytzenitmail.dk|
|elinstallatoer.dk|mx01.lytzenitmail.dk|
|elsker.dk|mx01.lytzenitmail.dk|
|elvis.dk|mx01.lytzenitmail.dk|
|fald.dk|mx01.lytzenitmail.dk|
|fedt.dk|mx01.lytzenitmail.dk|
|feminin.dk|mx01.lytzenitmail.dk|
|forening.dk|mx01.lytzenitmail.dk|
|gadefejer.dk|mx01.lytzenitmail.dk|
|gason.dk|mx01.lytzenitmail.dk|
|grin.dk|mx01.lytzenitmail.dk|
|grov.dk|mx01.lytzenitmail.dk|
|hardworking.dk|mx01.lytzenitmail.dk|
|heaven.dk|mx01.lytzenitmail.dk|
|hemmelig.dk|mx01.lytzenitmail.dk|
|huleboer.dk|mx01.lytzenitmail.dk|
|image.dk|mx01.lytzenitmail.dk|
|inbound.dk|mx01.lytzenitmail.dk|
|indbakke.dk|mx01.lytzenitmail.dk|
|infile.dk|mx01.lytzenitmail.dk|
|jyde.dk|mx01.lytzenitmail.dk|
|klog.dk|mx01.lytzenitmail.dk|
|knus.dk|mx01.lytzenitmail.dk|
|krudt.dk|mx01.lytzenitmail.dk|
|kulturel.dk|mx01.lytzenitmail.dk|
|larsen.dk|mx01.lytzenitmail.dk|
|lazy.dk|mx01.lytzenitmail.dk|
|lystig.dk|mx01.lytzenitmail.dk|
|mail.dia.dk|– (no A record either)|
|maskulin.dk|mx01.lytzenitmail.dk|
|min-postkasse.dk|mx01.lytzenitmail.dk|
|musling.dk|mx01.lytzenitmail.dk|
|natteliv.dk|mx01.lytzenitmail.dk|
|netbruger.dk|mx01.lytzenitmail.dk|
|pedal.dk|mx01.lytzenitmail.dk|
|pengemand.dk|mx01.lytzenitmail.dk|
|pokerface.dk|mx01.lytzenitmail.dk|
|post.dia.dk|– (no A record either)|
|postman.dk|mx01.lytzenitmail.dk|
|privat.dia.dk|– (no A record either)|
|quake.dk|mx01.lytzenitmail.dk|
|ready.dk|mx01.lytzenitmail.dk|
|secret.dk|mx01.lytzenitmail.dk|
|sleepy.dk|mx01.lytzenitmail.dk|
|sporty.dk|mx01.lytzenitmail.dk|
|superbruger.dk|mx01.lytzenitmail.dk|
|talent.dk|mx01.lytzenitmail.dk|
|tanke.dk|mx01.lytzenitmail.dk|
|taxidriver.dk|mx01.lytzenitmail.dk|
|teens.dk|mx01.lytzenitmail.dk|
|teknik.dk|mx01.lytzenitmail.dk|
|tjekket.dk|mx01.lytzenitmail.dk|
|traceroute.dk|mx01.lytzenitmail.dk|
|tv.dk|mailgate.cybercity.dk|
|ugenstilbud.dk|mx01.lytzenitmail.dk|
|ungdom.dk|mx01.lytzenitmail.dk|
|video.dk|mx01.lytzenitmail.dk|
|vittig.dk|mx01.lytzenitmail.dk|

**Comment by cketti** [comment]
We'll use this issue as a reminder to adjust the config.

**Comment by cketti** [comment]
I couldn't find any server settings for the domains that don't point to mail.jubii.dk (mobil.dk, film.dk, tv.dk).
