### ISSUE TITLE
Autoconfig for connected accounts (or missing documentation?)

### ISSUE THREAD

**Issue by Gabgobie** [thunderbird/autoconfig#122]
Hi,

this might be related to #20 but I was somewhat unsure since #20 seems to focus on the ISPDB side of things.

I am looking to provide my users with the best possible experience using thunderbird and have already successfully configured the autoconfig for mail, however I was unable to find anything on thunderbirds detection of connected accounts => LDAP, CardDAV, CalDAV. I did find the [MCD Docs](https://enterprise.thunderbird.net/deploy/mcd-thunderbird-autoconfig) but they only talk about configuring this using the prefs.js which is client-side.

I have seen thunderbird automatically detecting the contacts and calendars from gmail so I am somewhat sure that this feature is present.

Reading the ISPDB configuration for gmail didn't give me any insight into the mechanism used though.

My question boils down to:

- How can I provide "Google-style" autoconfig for my clients => not only mail but mail, contacts (ldap+carddav) and calendar?
- Is there documentation that I missed?

Best,
Gab

**Comment by Gabgobie** [comment]
Re-reading the [sample autoconfig](https://wiki.mozilla.org/Thunderbird:Autoconfiguration:ConfigFileFormat), I just found this line: `<!-- For CardDAV, CalDAV auto discovery, the mechanism from RFC 6764 is used -->`.

That would cover CardDAV and CalDAV. Unfortunately `_ldap._tcp` records are ignored and they wouldn't be sufficient for covering all settings necessary.

I assume that answers my questions in the following way:

- How can I provide...:
  - CalDAV + CardDAV -> RFC6764
  - LDAP -> not possible
- Yes

which is leading me to ask if there is any chance of support for LDAP configuration being added to the autoconfig.xml?

**Comment by cketti** [comment]
For Thunderbird feature requests, please use [Bugzilla](https://bugzilla.mozilla.org). [Bug 454568](https://bugzilla.mozilla.org/show_bug.cgi?id=454568) seems to be a good fit for this.

As far as I can tell, Thunderbird currently only supports automatically finding CardDAV settings. There doesn't seem to be any support for detecting LDAP settings.

**Comment by Gabgobie** [comment]
Thanks for pointing me in the right direction and looking into the matter.
