### ISSUE TITLE
smtp relay feature request

### ISSUE THREAD

**Issue by Djfe** [thunderbird/autoconfig#79]
It would be nice if the autoconfig would also be able to store infos about SMTP relay servers :)

**Comment by benbucksch** [comment]
Hi Felix, could you please explain a little more?
1) What is the use case, why you need this, from a mail client perspective? Is this required?
2) How often is this needed?
3) What info exactly would you need? For each information: why is this needed?
-- 
Sent from my phone. Please excuse the brevity.

**Comment by Djfe** [comment]
My thoughts on this stemmed from #38 and running across https://www.telekom.de/hilfe/apps-dienste/e-mail/einstellungen/smtp-relay-server while researching for #83
If also other types of software would start using autoconfig, then it could make sense to also put SMTP relay servers into it, cause why not.

Mailclients will rarely be using smtprelay servers or only by people knowdledgeable enough that they might not require an autoconfig.

1) I don't need this. This is purely optional. SMTP relay servers exist and their data format is very similar to `outgoingServer`.
2) I don't know.
3) They could also just be put into the existing autoconfig as another `outgoingServer` with the lowest priority, but since users cannot choose which of the configs to use in existing mail clients that might not make much sense.

If you don't see much advantage in implementing this, then we might as well let it be. Feel free to close this :)

**Comment by benbucksch** [comment]
> Mailclients will rarely be using SMTP relay servers

OK, let's consider it out of scope, then.
