### ISSUE TITLE
folder names for features like junk, trash, sent, drafts etc.

### ISSUE THREAD

**Issue by Djfe** [thunderbird/autoconfig#80]
It would be nice to have a way to add default names for certain folder types.
I experienced (in the past) how thunderbird didn't recognize the junk folder and created it's own for some servers. (not sure whether this is fixed, but this is something mail clients will experience from time to time)

**Comment by benbucksch** [comment]
Normally, the IMAP extension SPECIAL USE handles this.
Thunderbird implements this (I happen to know, because I implemented it myself, about a decade ago).
-- 
Sent from my phone. Please excuse the brevity.

29.12.2023 17:10:14 Felix Baumann ***@***.***>:

**Comment by Djfe** [comment]
thank you for the explanation :)
