### ISSUE TITLE
webMail loginPageInfo explain "waitForRedirectionURLPrefix"

### ISSUE THREAD

**Issue by Djfe** [thunderbird/autoconfig#82]
How is this attribute supposed to be interpreted/what is it used for? :)

I can imagine, but it would still be good to have a sentence explaining it in the specs:
https://www.bucksch.org/1/projects/thunderbird/autoconfiguration/config-file-format.html

example:
https://github.com/thunderbird/autoconfig/blob/master/ispdb/t-online.de.xml#L49

**Comment by ben221199** [comment]
@Djfe It seems that it is online used by T-Online. Maybe they made up this attribute.
